apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-monitor
spec:
  selector:
    matchLabels:
      name: myapp-monitor
  template:
    metadata:
      labels:
        name: myapp-monitor
    spec:
      containers:
        - name: ssd-monitor
          image: anandr72/ssd-monitor
