apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor-ds
spec:
  selector:
    matchLabels:
      app: myapp-monitor
  template:
    metadata:
      labels:
        app: myapp-monitor
    spec:
      containers:
      - name: main
        image: anandr72/ssd-monitor
